# Generated by Django 2.0.7 on 2018-07-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configUp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='power_rail_2',
        ),
        migrations.AlterField(
            model_name='config',
            name='power_rail_1',
            field=models.BooleanField(choices=[(0, 'Off'), (1, 'On')], default=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='power_rail_3',
            field=models.BooleanField(choices=[(0, 'Off'), (1, 'On')], default=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='power_rail_5',
            field=models.BooleanField(choices=[(0, 'Off'), (1, 'On')], default=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='power_rail_6',
            field=models.BooleanField(choices=[(0, 'Off'), (1, 'On')], default=True),
        ),
    ]
