# Generated by Django 2.0.7 on 2018-07-31 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configUp', '0004_auto_20180731_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='image_acquisition_profile',
            field=models.IntegerField(choices=[(0, '1600x1200'), (1, '640x480')]),
        ),
        migrations.AlterField(
            model_name='config',
            name='imu_accel_enabled',
            field=models.IntegerField(choices=[(0, 'Off'), (1, 'On')], default=False),
        ),
        migrations.AlterField(
            model_name='config',
            name='imu_gyro_enabled',
            field=models.IntegerField(choices=[(0, 'Off'), (1, 'On')], default=False),
        ),
        migrations.AlterField(
            model_name='config',
            name='imu_magno_enabled',
            field=models.IntegerField(choices=[(0, 'Off'), (1, 'On')], default=False),
        ),
        migrations.AlterField(
            model_name='config',
            name='power_rail_1',
            field=models.IntegerField(choices=[(0, 'Off'), (1, 'On')], default=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='power_rail_3',
            field=models.IntegerField(choices=[(0, 'Off'), (1, 'On')], default=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='power_rail_5',
            field=models.IntegerField(choices=[(0, 'Off'), (1, 'On')], default=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='power_rail_6',
            field=models.IntegerField(choices=[(0, 'Off'), (1, 'On')], default=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='reset_power_rail_1',
            field=models.IntegerField(choices=[(0, 'Off'), (1, 'On')], default=False),
        ),
        migrations.AlterField(
            model_name='config',
            name='reset_power_rail_2',
            field=models.IntegerField(choices=[(0, 'Off'), (1, 'On')], default=False),
        ),
        migrations.AlterField(
            model_name='config',
            name='reset_power_rail_3',
            field=models.IntegerField(choices=[(0, 'Off'), (1, 'On')], default=False),
        ),
        migrations.AlterField(
            model_name='config',
            name='reset_power_rail_4',
            field=models.IntegerField(choices=[(0, 'Off'), (1, 'On')], default=False),
        ),
        migrations.AlterField(
            model_name='config',
            name='reset_power_rail_5',
            field=models.IntegerField(choices=[(0, 'Off'), (1, 'On')], default=False),
        ),
        migrations.AlterField(
            model_name='config',
            name='reset_power_rail_6',
            field=models.IntegerField(choices=[(0, 'Off'), (1, 'On')], default=False),
        ),
        migrations.AlterField(
            model_name='config',
            name='self_test',
            field=models.IntegerField(choices=[(0, 'Off'), (1, 'On')], default=False),
        ),
        migrations.AlterField(
            model_name='config',
            name='user_submitted',
            field=models.CharField(default='uos3', max_length=64),
        ),
    ]
