# Generated by Django 2.2.dev20180608064004 on 2018-10-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configUp', '0005_auto_20180731_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
