# Generated by Django 2.2.dev20180608064004 on 2019-02-12 14:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configUp', '0006_config_date_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='power_rail_2',
            field=models.IntegerField(choices=[(0, 'Off'), (1, 'On')], default=True),
        ),
        migrations.AddField(
            model_name='config',
            name='power_rail_4',
            field=models.IntegerField(choices=[(0, 'Off'), (1, 'On')], default=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='batt_overtemp',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)]),
        ),
        migrations.AlterField(
            model_name='config',
            name='configuration_acquisition_interval',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)]),
        ),
        migrations.AlterField(
            model_name='config',
            name='downlink_stop_time',
            field=models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4294967295)]),
        ),
        migrations.AlterField(
            model_name='config',
            name='gps_acquisition_interval',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)]),
        ),
        migrations.AlterField(
            model_name='config',
            name='gps_sample_count',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(16)]),
        ),
        migrations.AlterField(
            model_name='config',
            name='gps_sample_interval',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(2550)]),
        ),
        migrations.AlterField(
            model_name='config',
            name='health_acquisition_interval',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)]),
        ),
        migrations.AlterField(
            model_name='config',
            name='image_acquisition_time',
            field=models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4294967295)]),
        ),
        migrations.AlterField(
            model_name='config',
            name='imu_acquisition_interval',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)]),
        ),
        migrations.AlterField(
            model_name='config',
            name='imu_sample_count',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(16)]),
        ),
        migrations.AlterField(
            model_name='config',
            name='imu_sample_interval',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(2550)]),
        ),
        migrations.AlterField(
            model_name='config',
            name='low_voltage_recovery',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(25.5)]),
        ),
        migrations.AlterField(
            model_name='config',
            name='low_voltage_threshold',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(25.5)]),
        ),
        migrations.AlterField(
            model_name='config',
            name='obc_overtemp',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)]),
        ),
        migrations.AlterField(
            model_name='config',
            name='pa_overtemp',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)]),
        ),
        migrations.AlterField(
            model_name='config',
            name='rx_overtemp',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)]),
        ),
        migrations.AlterField(
            model_name='config',
            name='time',
            field=models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4294967295)]),
        ),
        migrations.AlterField(
            model_name='config',
            name='tx_interval',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)]),
        ),
        migrations.AlterField(
            model_name='config',
            name='tx_overtemp',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)]),
        ),
    ]
