# Generated by Django 2.2.dev20180608064004 on 2019-03-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configUp', '0007_auto_20190212_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='tx_enable',
            field=models.BooleanField(choices=[(0, 'Off'), (1, 'On')], default=True),
        ),
    ]
